In [1]:
my_list=[1,2,3]

In [2]:
import numpy as np

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
arr=np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
 np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [22]:
np.random.rand(5)

array([0.92981838, 0.63608174, 0.92739016, 0.21793753, 0.43512796])

In [23]:
np.random.rand(5,5)

array([[0.22994168, 0.95706388, 0.99868861, 0.7955822 , 0.76997177],
       [0.18358452, 0.18123845, 0.01744083, 0.17684362, 0.38852977],
       [0.39556547, 0.67429418, 0.99284254, 0.06215833, 0.7869897 ],
       [0.93824582, 0.52777217, 0.78273785, 0.45479527, 0.21826405],
       [0.79682431, 0.61884755, 0.06298463, 0.86724373, 0.52151309]])

In [24]:
np.random.randn(2)

array([ 0.23938379, -1.121925  ])

In [29]:
np.random.randint(1,100,5)

array([42, 55, 77, 68, 47])

In [30]:
arr=np.arange(25)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
ranarr=np.random.randint(0,50,10)

In [33]:
ranarr

array([38, 30, 48, 34, 40, 44, 36, 43, 15, 36])

In [37]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
ranarr.max()

48

In [39]:
ranarr.min()

15

In [40]:
ranarr.argmax()

2

In [41]:
ranarr.argmin()

8

In [43]:
arr.shape

(25L,)

In [44]:
arr=arr.reshape(5,5)

In [45]:
arr.shape

(5L, 5L)

In [47]:
arr.dtype

dtype('int32')